version: 1.0.{build}
configuration:
- Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\DeepStreamNet.sln" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\DeepStreamNet.sln" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
skip_tags: true
image: Visual Studio 2015