version: 0.0.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
pull_requests:
  do_not_increment_build_number: true
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
skip_tags: true
test: off
build_script:
  - ps: dotnet --info  
  - ps: dotnet restore .\src\DeepStreamNet
  - ps: dotnet build -c Release .\src\DeepStreamNet
  - ps: dotnet pack -c Release --no-build --include-symbols .\src\DeepStreamNet
artifacts:
- path: src\DeepStreamNet\bin\Release\*.nupkg