language: csharp  
sudo: required  
dist: trusty  
dotnet: 1.0.0-preview2-1-003177
env:  
  - DOTNETCORE=1 DOTNET_CLI_TELEMETRY_OPTOUT=1
mono:  
  - none
os:  
  - linux
  - osx
osx_image: xcode7.3  

script:
  - dotnet restore
  - dotnet build src/DeepStreamNet -f netstandard1.5